### PR TITLE
if comment_empty is set to false, also check if line length is less than  1 and return

### PR DESCRIPTION
**Pull request by rmagillxyz**

### CODE REVIEW

**Comment by terrortylor** [comment]
I'm not sure what use case this is for, could you help me understand?

**Comment by rmagillxyz** [comment]
yeah, so say you have a block above or below the cursor, but have a few empty lines between the cursor and the start of the block, this will prevent those additional empty lines from ending up as part of the block's comments. Also, if you have lines between a block with only whitespace (not empty, but white), it will be considered as part of the block, but not leave a comment. This is how Tim Pope's plugin behaved. Good job btw. Thanks for your work.

**Comment by rmagillxyz** [comment]
As far as use cases, it just allows you to be a little more loose with block comments. Instead of moving the cursor all the way to the block to get the perfect lengthed comment, you can do it from where you are as long as that block is your next neighbor. I use block comments all the time so I noticed this right away. I left `comment_empty` as true since I figured you wanted this as default behavior, but if you set it to false, it should see the difference.

**Comment by rmagillxyz** [comment]
My bad dude. I just switched back to your copy and now the `comment_empty` is working as expected. It must have been an issue on my end. I've been working out a lot of kinks in my lua config so I can't even figure out what my issue was now. Disregard. Great job btw. Thanks for your work.

**Pull request closed without merging**
